export const locations: {
  id: string;
  name: string;
  date: string;
  location: string;
  lumaLink: string;
  joinLink: string;
  instagramLink?: string;
  twitterLink?: string;
  youtubeLink?: string;
  websiteLink?: string;
  coordinates: [number, number];
  nodeCity: string;
  nodeCountry: string;
  imageSrc?: string;
}[] = [
  {
    id: "waterloo",
    name: "Socratica",
    date: "MARCH 2022",
    location: "Waterloo, ON",
    lumaLink: "https://lu.ma/embed/calendar/cal-cBMgU2QXqXZQSv1/events",
    joinLink: "https://lu.ma/socratica",
    instagramLink: "https://www.instagram.com/socratica.info",
    twitterLink: "https://twitter.com/socraticainfo",
    youtubeLink: "https://www.youtube.com/@socraticainfo",
    websiteLink: "https://www.socratica.info/",
    coordinates: [43.477305, -80.549252],
    nodeCity: "Waterloo",
    nodeCountry: "CAN",
    imageSrc: "/lattice/waterloo.jpg",
  },
  {
    id: "toronto",
    name: "Meraki",
    date: "JANUARY 2023",
    location: "Toronto, ON",
    lumaLink: "https://lu.ma/embed/calendar/cal-n1HampGEkGvGtrZ/events",
    joinLink: "https://lu.ma/user/usr-n1HampGEkGvGtrZ",
    coordinates: [43.664714, -79.385477],
    nodeCity: "Toronto",
    nodeCountry: "CAN",
    imageSrc: "/lattice/toronto.jpeg",
  },
  {
    id: "vancouver",
    name: "Atelier",
    date: "SEPTEMBER 2023",
    location: "Vancouver, BC",
    lumaLink: "https://lu.ma/embed/calendar/cal-CvuDnsONPxinxqk/events",
    joinLink: "https://lu.ma/atelier.place",
    instagramLink: "https://www.instagram.com/atelier.place/",
    twitterLink: "https://x.com/atelier_place",
    websiteLink: "http://www.atelier.place/",
    coordinates: [49.2600924, -123.2509564],
    nodeCity: "Vancouver",
    nodeCountry: "CAN",
    imageSrc: "/lattice/vancouver.jpg",
  },
  {
    id: "cambridge-uk",
    name: "Scale Down",
    date: "OCTOBER 2023",
    location: "Cambridge, UK",
    lumaLink: "https://lu.ma/embed/calendar/cal-vHCyjMqqjpdduOt/events",
    joinLink: "https://lu.ma/scaledown",
    coordinates: [52.205338, 0.121817],
    nodeCity: "Cambridge",
    nodeCountry: "UK",
    imageSrc: "/lattice/cambridge-uk.png",
  },
  //   {
  //     id: "ottawa",
  //     name: "Agora",
  //     date: "OCTOBER 2023",
  //     location: "Ottawa, ON",
  //     lumaLink:
  //       "https://lu.ma/embed/calendar/cal-xPDTKP81aHIflKD/events",
  //     joinLink: "https://lu.ma/agora",
  //     instagramLink: "https://www.instagram.com/agora.cu",
  //     twitterLink: "https://twitter.com/socraticainfo",
  //     youtubeLink: "https://www.youtube.com/@socraticainfo",
  //     websiteLink: "https://www.socratica.info/",
  //     coordinates: [45.42153, -75.697193],
  //   },
  {
    id: "kingston",
    name: "id8.blankcanvas",
    date: "OCTOBER 2023",
    location: "Kingston, ON",
    lumaLink: "https://lu.ma/embed/calendar/cal-AxzTU0DF1vlwRSI/events",
    joinLink: "https://lu.ma/id8id8id8",
    instagramLink: "https://www.instagram.com/id8id8id8",
    coordinates: [44.231172, -76.485954],
    nodeCity: "Kingston",
    nodeCountry: "CAN",
    imageSrc: "/lattice/kingston.png",
  },
  // {
  //   id: "berkeley",
  //   name: "Side Project Sundays",
  //   date: "SEPTEMBER 2023",
  //   location: "Berkeley, CA",
  //   lumaLink: "https://lu.ma/embed/calendar/cal-CRtUehgIQHLEB3o/events",
  //   joinLink: "https://lu.ma/commonroom",
  //   instagramLink: "https://www.instagram.com/berkeleycommonroom",
  //   coordinates: [37.871593, -122.272747],
  //   nodeCity: "Berkeley",
  //   nodeCountry: "USA",
  // },
  {
    id: "western",
    name: "Momentum",
    date: "SEPTEMBER 2023",
    location: "London, ON",
    lumaLink: "https://lu.ma/embed/calendar/cal-gt0OmSf2cUw1HHl/events",
    joinLink: "https://lu.ma/moment.um",
    instagramLink: "https://www.instagram.com/momentum_uwo",
    coordinates: [43.009561, -81.275471],
    nodeCity: "London",
    nodeCountry: "CAN",
    imageSrc: "/lattice/western.png",
  },
  {
    id: "mit",
    name: "Friendly Beans",
    date: "DECEMBER 2023",
    location: "Cambridge, MA",
    lumaLink: "https://lu.ma/embed/calendar/cal-yDZTDnxoCpg2xwE/events",
    joinLink: "https://lu.ma/beans",
    coordinates: [42.3629, -71.0839],
    nodeCity: "Boston",
    nodeCountry: "USA",
    imageSrc: "/lattice/boston.jpg",
  },
  {
    id: "san-francisco",
    name: "Playspace",
    date: "JANUARY 2024",
    location: "San Francisco, CA",
    lumaLink: "https://lu.ma/embed/calendar/cal-WrTTBMGBVUcTaij/events",
    joinLink: "https://lu.ma/playspace",
    instagramLink: "https://www.instagram.com/socratica.info",
    coordinates: [37.7937, -122.3965],
    nodeCity: "San Francisco",
    nodeCountry: "USA",
    imageSrc: "/lattice/sf.png",
  },
  // {
  //   id: "stanford",
  //   name: "untitled",
  //   date: "JANUARY 2024",
  //   location: "Stanford, CA",
  //   lumaLink: "https://lu.ma/embed/calendar/cal-bBCpTcywZinszKP/events",
  //   joinLink: "https://lu.ma/untitled",
  //   coordinates: [37.4277, -122.1701],
  //   nodeCity: "Stanford",
  //   nodeCountry: "USA",
  // },
  {
    id: "usc",
    name: "Sundays",
    date: "JANUARY 2024",
    location: "Los Angeles, CA",
    lumaLink: "https://lu.ma/embed/calendar/cal-81AnmgiInWOKNmv/events",
    joinLink: "https://lu.ma/calendar/cal-81AnmgiInWOKNmv",
    instagramLink: "https://www.instagram.com/sundaysatusc",
    websiteLink: "https://www.sundays.rsvp/",
    coordinates: [34.0224, -118.2851],
    nodeCity: "Los Angeles",
    nodeCountry: "USA",
    imageSrc: "/lattice/la.jpg",
  },
  {
    id: "montreal",
    name: "Douze a Deux",
    date: "SEPTEMBER 2023",
    location: "Montreal, QC",
    lumaLink: "https://lu.ma/embed/calendar/cal-PIrfoWlJDawpNDO/events",
    joinLink: "https://lu.ma/douzeadeuxMontreal",
    coordinates: [45.5017, -73.5673],
    nodeCity: "Montreal",
    nodeCountry: "CAN",
    imageSrc: "/lattice/montreal.jpg",
  },
  {
    id: "washington",
    name: "Saturdays",
    date: "NOVEMEBER 2023",
    location: "Seattle, WA",
    lumaLink: "https://lu.ma/embed/calendar/cal-SD9FoHuZW6pQn6D/events",
    joinLink: "https://lu.ma/uwsaturdays",
    websiteLink: "https://saturdays.rsvp/",
    instagramLink: "https://www.instagram.com/saturdays.rsvp/",
    coordinates: [47.6062, -122.3321],
    nodeCity: "Seattle",
    nodeCountry: "USA",
    imageSrc: "/lattice/washington.png",
  },
  // {
  //   id: "unc",
  //   name: "Hatch",
  //   date: "JANUARY 2024",
  //   location: "Chapel Hill, NC",
  //   lumaLink: "https://lu.ma/embed/calendar/cal-p0CcDhZn6Z5elyX/events",
  //   joinLink: "https://lu.ma/unc-hatch",
  //   coordinates: [35.9049, -79.0469],
  //   nodeCity: "Chapel Hill",
  //   nodeCountry: "USA",
  // },
  {
    id: "imperial",
    name: "Craft",
    date: "JANUARY 2024",
    location: "London, UK",
    lumaLink: "https://lu.ma/embed/calendar/cal-qFfyVkBdmPJ7yBv/events",
    joinLink: "https://lu.ma/craft_",
    coordinates: [51.4988, -0.1749],
    nodeCity: "London",
    nodeCountry: "UK",
    imageSrc: "/lattice/imperial.jpg",
  },
  {
    id: "oxford",
    name: "Orchard",
    date: "SEPTEMBER 2024",
    location: "London, UK",
    lumaLink: "https://lu.ma/embed/calendar/cal-TGGXNEITTevMhOG/events",
    joinLink: "https://lu.ma/orchard",
    instagramLink: "https://www.instagram.com/orchard.oxford/",
    coordinates: [51.752, -1.2577],
    nodeCity: "Oxford",
    nodeCountry: "UK",
    imageSrc: "/lattice/oxford.jpg",
  },
  // {
  //   id: "tokyo",
  //   name: "ichinichiippo",
  //   date: "JANUARY 2024",
  //   location: "Tokyo, Japan",
  //   lumaLink: "https://lu.ma/embed/calendar/cal-vyilWokPjL5xHKF/events",
  //   joinLink: "https://lu.ma/ichinichi-ippo",
  //   instagramLink: "https://www.instagram.com/_ichinichiippo/",
  //   twitterLink: "https://twitter.com/socraticainfo",
  //   youtubeLink: "https://www.youtube.com/@socraticainfo",
  //   websiteLink: "https://www.socratica.info/",
  //   coordinates: [35.6895, 139.6917],
  // },
  {
    id: "philly",
    name: "Code & Coffee",
    date: "SEPTEMBER 2024",
    location: "Philadelphia, PA",
    lumaLink: "https://lu.ma/embed/calendar/cal-ftxaA6PDR5Tbllt/events",
    joinLink: "https://lu.ma/code-and-coffee",
    coordinates: [39.9500592, -75.1707463],
    nodeCity: "Philadelphia",
    nodeCountry: "USA",
  },
  {
    id: "ny",
    name: "Cozy Sundays",
    date: "APRIL 2024",
    location: "New York, NY",
    lumaLink: "https://lu.ma/cozy-sundays",
    joinLink:
      "https://www.notion.so/straightupjac/Socratica-NYC-public-5e1198e16be24eacae4d97f764717f21",
    websiteLink:
      "https://www.notion.so/straightupjac/Socratica-NYC-public-5e1198e16be24eacae4d97f764717f21",
    coordinates: [40.7128, -74.006],
    nodeCity: "New York City",
    nodeCountry: "USA",
    imageSrc: "http://straightupjac.xyz/socratica-nyc-cozy-sundays.png",
  },
  {
    id: "umn",
    name: "making@umn",
    date: "MARCH 2024",
    location: "Minneapolis, MN",
    lumaLink: "https://lu.ma/embed/calendar/cal-0U8g6FXtpy0P1ih/events",
    joinLink: "https://lu.ma/making-umn",
    instagramLink: "https://www.instagram.com/makingatumn/",
    websiteLink: "https://making.mn/",
    coordinates: [44.9754, -93.2331],
    nodeCity: "Minnesota",
    nodeCountry: "USA",
    imageSrc: "/lattice/umn.png",
  },
  {
    id: "morocco",
    name: "ALTs Morocco",
    date: "NOVEMBER 2024",
    location: "Rabat, Morocco",
    lumaLink: "https://lu.ma/embed/calendar/cal-PWXzFvN0nlL0D4R/events",
    joinLink: "https://lu.ma/alts.morocco",
    instagramLink: "https://www.instagram.com/alts.morocco",
    twitterLink: "https://x.com/altsmorocco",
    coordinates: [34.0084, -6.8539],
    nodeCity: "Rabat",
    nodeCountry: "MOROCCO",
    imageSrc: "/lattice/morocco.png",
  },
  {
    id: "halifax",
    name: "Collect",
    date: "OCTOBER 2024",
    location: "Halifax, NS",
    lumaLink: "https://lu.ma/embed/calendar/cal-VLkFm9DKIHxx0HF/events",
    joinLink: "https://lu.ma/CollectHalifax",
    coordinates: [44.6509, -63.5923],
    nodeCity: "Halifax",
    nodeCountry: "CAN",
    imageSrc: "/lattice/halifax.png",
  },
  {
    id: "victoria",
    name: "Tenfold",
    date: "MAY 2024",
    location: "Victoria, BC",
    lumaLink: "https://lu.ma/embed/calendar/cal-ChvmXj1B1x2n23o/events",
    joinLink: "https://lu.ma/tenfold",
    websiteLink: "https://www.tenfoldvictoria.com/",
    coordinates: [48.4284, -123.3656],
    nodeCity: "Victoria",
    nodeCountry: "CAN",
    imageSrc: "/lattice/victoria.png",
  },
  {
    id: "hamilton",
    name: "Agora",
    date: "SEPTEMBER 2024",
    location: "Hamilton, ON",
    lumaLink: "https://lu.ma/embed/calendar/cal-ImDNuyKTF00fOYK/events",
    joinLink: "https://lu.ma/theagora",
    instagramLink: "https://www.instagram.com/agora.meet",
    coordinates: [43.2614, -79.9197],
    nodeCity: "Hamilton",
    nodeCountry: "CAN",
    imageSrc: "/lattice/hamilton.png",
  },
];
